truncate table amazon_product_type;
truncate table amazon_product_type;
insert into amazon_product_type (version, spreadshirt_product_type_id, name, clothing_type, department1, department2, department3, browse_node,  outer_material, inner_material, material_composition,care_instructions, size_modifier, sleeve_type, collar_type, platinum_keywords1, platinum_keywords2, platinum_keywords3, platinum_keywords4, platinum_keywords5)
values 
(0,"3","Männer Standard T-Shirt","Shirt","Herren","Jungen","","305555031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"5","Männer Pullover","Sweater","Herren","Jungen","","78700031","Baumwolle","Baumwolle","80% Baumwolle, 20% Polyester","von links waschen, bis maximal 30°C"," ","Lang - regulär","Rundhals","Sweatshirt","Sweatshirts","Hoodie","Hoodies","Sweater, Sweaters"),
(0,"6","Männer T-Shirt klassisch","Shirt","Herren","Jungen","","305555031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"15","Baseballkappe","Hat","Unisex - Erwachsene","Herren","Damen","671775011","Baumwolle","Baumwolle","100% Baumwolle",""," ","Ohne Arm"," ","Baseball Cap","Baseball Caps","Baseballcap","Baseballcaps","Cap, Caps, Schirmmütze, Schirmmützen"),
(0,"20","Männer Kapuzenpullover","Sweater","Herren","Jungen","","78700031","Baumwolle","Fleece","80% Baumwolle, 20% Polyester","von links waschen, bis maximal 30°C"," ","Lang - regulär","Rundhals","Sweatshirt","Sweatshirts","Hoodie","Hoodies","Sweater, Sweaters"),
(0,"23","Männer Langarmshirt","Shirt","Herren","Jungen","","305557031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","Lang - regulär","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"25","Männer Poloshirt klassisch","Shirt","Herren","Jungen","","305556031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","Polo","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"36","Männer langärmeliges Baseballshirt","Shirt","Herren","Jungen","","305557031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","Lang - regulär","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"48","Kinder T-Shirt klassisch","Shirt","Unisex - Kinder","Jungen","Mädchen","305555031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"51","Wintermütze","Hat","Unisex - Erwachsene","Herren","Damen","305533031","Acryl","Acryl","100% Acryl",""," ","Ohne Arm"," ","Mütze","Mützen","Kopfbedeckung","Kopfbedeckungen","Hut"),
(0,"54","Schal","Accessory","Unisex - Erwachsene","Herren","Damen","78793031","Polyester","Polyester","100% Polyester",""," ","Ohne Arm"," ","Schal","Schals","Halstuch","Halstücher",""),
(0,"57","Frauen Pullover","Sweater","Damen","Mädchen","","78700031","Baumwolle","Baumwolle","80% Baumwolle, 20% Polyester","von links waschen, bis maximal 30°C"," ","Lang - regulär","Rundhals","Sweatshirt","Sweatshirts","Hoodie","Hoodies","Sweater, Sweaters"),
(0,"64","Männer Sportjacke","Outerwear","Herren","Jungen","","78741031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","Lang - regulär","Rundhals","Jacke","Jacken","","",""),
(0,"69","Männer Kontrast-Shirt","Shirt","Herren","Jungen","","305555031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"70","Männer Ländershirt","Shirt","Herren","Jungen","","305555031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"84","Männer Slim Fit T-Shirt","Shirt","Herren","Jungen","","305555031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"93","Männer Kapuzenjacke","Sweater","Herren","Jungen","","78700031","Baumwolle","Fleece","80% Baumwolle, 20% Polyester","von links waschen, bis maximal 30°C"," ","Lang - regulär","Rundhals","Sweatshirt","Sweatshirts","Hoodie","Hoodies","Sweater, Sweaters"),
(0,"95","Frauen Girlieshirt","Shirt","Damen","Mädchen","","305555031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"101","Frauen AA Langarm-Kapuzenshirt","Shirt","Damen","Mädchen","","305557031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","Lang - regulär","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"108","Weihnachtsmütze","Hat","Unisex - Erwachsene","Herren","Damen","305533031","Acryl","Acryl","100% Acryl",""," ","Ohne Arm"," ","Weihnachtshut","Zipfelmütze","Weihnachtskostüm","Weihnachtshut",""),
(0,"114","Männer Kurzärmeliges Baseballshirt","Shirt","Herren","Jungen","","305555031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"123","Frauen Spaghetti Top","Shirt","Damen","Mädchen","","78690031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","Ohne Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"141","Kochschürze","Accessory","Unisex - Erwachsene","Herren","Damen","305531031","Polyester","Baumwolle","65% Polyester, 35% Baumwolle",""," ","Ohne Arm"," ","Schürze","Schürzen","Grillschürze","Grillschürzen","Kochschürzen"),
(0,"144","Männer Retro-T-Shirt","Shirt","Herren","Jungen","","305555031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"146","Männer Retroshorts","Underwear","Herren","Jungen","","78760031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","Ohne Arm","Rundhals","Boxershorts","Unterwäsche","Unterhose","Unterhosen",""),
(0,"148","Männer Muskelshirt","Shirt","Herren","Jungen","","305555031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","Ohne Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"160","Frauen Hotpants","Underwear","Damen","Mädchen","","78759031","Baumwolle","Baumwolle","95% Baumwolle, 5% Elastan","von links waschen, bis maximal 30°C"," ","Ohne Arm"," ","Hose","Hosen","Höschen","Unterwäsche",""),
(0,"172","Frauen Schulterfreies Tank Top","Shirt","Damen","Mädchen","","78690031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","Ohne Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"174","Männer AA Langarmshirt","Shirt","Herren","Jungen","","305557031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","Lang - regulär","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"175","Männer AA T-Shirt","Shirt","Herren","Jungen","","305555031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"202","Baby Bio-Langarmshirt","Shirt","Unisex - Baby","Baby - Jungen","Baby - Mädchen","305557031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","Lang - regulär","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"207","Frauen Used-Look-Kapuzenpullover","Sweater","Damen","Mädchen","","78700031","Baumwolle","Baumwolle","80% Baumwolle, 20% Polyester","von links waschen, bis maximal 30°C"," ","Lang - regulär","Rundhals","Sweatshirt","Sweatshirts","Hoodie","Hoodies","Sweater, Sweaters"),
(0,"209","Frauen Langarmshirt","Shirt","Damen","Mädchen","","305557031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","Lang - regulär","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"216","Frauen Kontrast-Shirt","Shirt","Damen","Mädchen","","305555031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"266","Männer Sommer-Shirt","Shirt","Herren","Jungen","","305555031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"267","Frauen Sommer-Shirt","Shirt","Damen","Mädchen","","305555031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"281","Männer Poloshirt","Shirt","Herren","Jungen","","305556031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","Polo","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"288","Frauen AA T-Shirt","Shirt","Damen","Mädchen","","305555031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"300","Frauen AA ¾-Arm Top","Shirt","Damen","Mädchen","","305557031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","3/4-Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"302","Standardshirt Männer","Shirt","Herren","Jungen","","305555031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"342","Baby Bio-Langarm-Body","Sleepwear","Unisex - Baby","Baby - Jungen","Baby - Mädchen","305557031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","Lang - regulär","Rundhals","Body","Babybody","Babystrampler","Strampler","Babyanzug, Krabbelanzug"),
(0,"357","Männer Dickies Kapuzenjacke","Sweater","Herren","Jungen","","78700031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","Lang - regulär","Rundhals","Sweatshirt","Sweatshirts","Hoodie","Hoodies","Sweater, Sweaters"),
(0,"361","Männer AA Bio-Shirt","Shirt","Herren","Jungen","","305555031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"362","Frauen AA Bio-Shirt","Shirt","Damen","Mädchen","","305555031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"368","Frauen Bio-T-Shirt","Shirt","Damen","Mädchen","","305555031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"369","Männer Bio-T-Shirt","Shirt","Herren","Jungen","","305555031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"372","Frauen V-Longshirt","Shirt","Damen","Mädchen","","305557031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","Ohne Arm","V-Ausschnitt","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"375","Baby Bio-Kurzarmshirt","Shirt","Unisex - Baby","Baby - Jungen","Baby - Mädchen","364885011","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"376","Baby Bio-Mütze","Hat","Unisex - Baby","Baby - Jungen","Baby - Mädchen","357615011","Baumwolle","Baumwolle","100% Baumwolle",""," ","Ohne Arm"," ","Mütze","Mützen","Babymütze","Babymützen",""),
(0,"377","Frauen Schwangerschafts-Top","Shirt","Damen","Mädchen","","78690031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C","Umstandsmode","1/2-Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"379","Frauen Poloshirt","Shirt","Damen","Mädchen","","305556031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"381","Kinder Poloshirt","Shirt","Unisex - Kinder","Jungen","Mädchen","305556031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"428","Flexfit Baseballkappe","Hat","Unisex - Erwachsene","Herren","Damen","671775011","Polyester","Baumwolle","63% Polyester, 34% Baumwolle, 3% Elastan",""," ","Ohne Arm"," ","Baseball Cap","Baseball Caps","Baseballcap","Baseballcaps","Cap, Caps, Schirmmütze, Schirmmützen"),
(0,"430","Männer T-Shirt atmungsaktiv","Shirt","Herren","Jungen","","305555031","Polyester","Polyester","85% Polyester, 15% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"444","Frauen Kapuzenpullover","Sweater","Damen","Mädchen","","78700031","Baumwolle","Fleece","80% Baumwolle, 20% Polyester","von links waschen, bis maximal 30°C"," ","Lang - regulär","Rundhals","Sweatshirt","Sweatshirts","Hoodie","Hoodies","Sweater, Sweaters"),
(0,"445","Frauen Kapuzenjacke","Sweater","Damen","Mädchen","","78700031","Baumwolle","Fleece","80% Baumwolle, 20% Polyester","von links waschen, bis maximal 30°C"," ","Lang - regulär","Rundhals","Sweatshirt","Sweatshirts","Hoodie","Hoodies","Sweater, Sweaters"),
(0,"457","Kinder Bio-T-Shirt","Shirt","Unisex - Kinder","Jungen","Mädchen","305555031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"461","Frauen T-Shirt klimaneutral","Shirt","Damen","Mädchen","","305555031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"463","Frauen Ländershirt","Shirt","Damen","Mädchen","","305555031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"464","Kinder Ländershirt","Shirt","Unisex - Kinder","Jungen","Mädchen","305555031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"483","Kinder Kapuzenpullover","Sweater","Unisex - Kinder","Jungen","Mädchen","78700031","Baumwolle","Fleece","50% Baumwolle, 50% Polyester","von links waschen, bis maximal 30°C"," ","Lang - regulär","Rundhals","Sweatshirt","Sweatshirts","Hoodie","Hoodies","Sweater, Sweaters"),
(0,"487","Kinder Kontrast-Shirt","Shirt","Unisex - Kinder","Jungen","Mädchen","305555031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"492","Adidas mens Tee","Shirt","Herren","Jungen","","305555031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"493","Adidas womens Tee ","Shirt","Damen","Mädchen","","305555031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"494","Kinder Langarm-Baseballshirt","Shirt","Unisex - Kinder","Jungen","Mädchen","305557031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","Lang - regulär","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"495","Kinder Langarm-Shirt","Shirt","Unisex - Kinder","Jungen","Mädchen","305557031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","Lang - regulär","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"510","Männer Recycled T-Shirt","Shirt","Herren","Jungen","","305555031","Baumwolle","Baumwolle","69% Baumwolle, 29% Polyacryl, 2% Polyester","von links waschen, bis maximal 30°C"," ","1/2-Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"526","Krawatte","Accessory","Herren","Jungen","","78795031","Polyester","Polyester","100% Polyester",""," ","Ohne Arm"," ","Schlips","Langbinder","Binder","",""),
(0,"530","Handschuhe","Accessory","Unisex - Erwachsene","Herren","Damen","78794031","Wolle","Wolle","100% Wolle",""," ","Ohne Arm"," ","Handschuh","Wollhandschuh","Wollhandschuhe","Handschuhe","Winterhandschuhe"),
(0,"538","Unisex AA V-Shirt","Shirt","Unisex - Erwachsene","Herren","Damen","305555031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","V-Ausschnitt","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"539","Frauen Langarm-V-Shirt","Shirt","Damen","Mädchen","","305557031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","Lang - regulär","V-Ausschnitt","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"543","Männer T-Shirt Barking Irons","Shirt","Herren","Jungen","","305555031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"549","Männer Langarm-Poloshirt","Shirt","Herren","Jungen","","305556031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","Lang - regulär","Polo","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"553","Frauen Camisole Top","Shirt","Damen","Mädchen","","78690031","Baumwolle","Baumwolle","95% Baumwolle, 5% Elastan","von links waschen, bis maximal 30°C"," ","Ohne Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"555","Frauen Sweatpants","Pants","Damen","Mädchen","","305530031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","Ohne Arm"," ","Hose","Hosen","Sporthose","Sporthosen","Freizeithose, Yogahose"),
(0,"560","Babys Body","Sleepwear","Unisex - Baby","Baby - Jungen","Baby - Mädchen","357619011","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","Rundhals","Body","Babybody","Babystrampler","Strampler",""),
(0,"561","Frauen T-Shirt mit U-Ausschnitt","Shirt","Damen","Mädchen","","305555031","Baumwolle","Baumwolle","98% Baumwolle, 2% Elastan","von links waschen, bis maximal 30°C"," ","1/2-Arm","U-Boot","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"562","Frauen T-Shirt mit V-Ausschnitt","Shirt","Damen","Mädchen","","305555031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","V-Ausschnitt","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"565","Frauen Doppel-V-Shirt","Shirt","Damen","Mädchen","","305555031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","V-Ausschnitt","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"567","Frauen T-Shirt atmungsaktiv","Shirt","Damen","Mädchen","","305555031","Lyocell","Lyocell","67% Lyocell, 29% Baumwolle, 4%Elastan","von links waschen, bis maximal 30°C"," ","1/2-Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"570","Männer T-Shirt mit Brusttasche von American Apparel","Shirt","Herren","Jungen","","305555031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"571","Männer Kontrast-T-Shirt meliert von American Apparel","Shirt","Herren","Jungen","","305555031","Baumwolle","Baumwolle","70% Baumwolle, 30% Polyester","von links waschen, bis maximal 30°C"," ","1/2-Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"574","Männer Sweatpants von American Apparel","Pants","Herren","Jungen","","305530031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","Ohne Arm"," ","Hose","Hosen","Sporthose","Sporthosen","Freizeithose, Freizeithosen, Laufhose, Laufhosen"),
(0,"575","Frauen Shirt Scoop Neck schulterfrei","Shirt","Damen","Mädchen","","305555031","Baumwolle","Baumwolle","55% Baumwolle, 45% Polyester","von links waschen, bis maximal 30°C"," ","Ohne Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"580","Women's AA Racerback Tank Dress","Dress","Damen","Mädchen","","78732031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","Ohne Arm","Rundhals","Kleid","Kleider","Röckchen","Rock","Röcke"),
(0,"584","Frauen Rock","Skirt","Damen","Mädchen","","78728031","Viskose","Viskose","70% Viskose aus Bambus, 25% Baumwolle, 5% Elastan","von links waschen, bis maximal 30°C"," ","Ohne Arm"," ","Rock","Röcke","Röckchen","",""),
(0,"593","Leichter Schal von AA","Accessory","Unisex - Erwachsene","Herren","Damen","78793031","Baumwolle","Baumwolle","100% Baumwolle",""," ","Ohne Arm"," ","Schal","Schals","Halstuch","Halstücher",""),
(0,"594","Kapuzenjacke von American Apparel","Sweater","Herren","Jungen","","78700031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","Lang - regulär","Rundhals","Sweatshirt","Sweatshirts","Hoodie","Hoodies","Sweater, Sweaters"),
(0,"601","Baby AA Langarmshirt","Shirt","Unisex - Baby","Baby - Jungen","Baby - Mädchen","305557031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","Lang - regulär","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"602","Kinder Langarmshirt von American Apparel","Shirt","Unisex - Kinder","Jungen","Mädchen","305557031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","Lang - regulär","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"604","Kinder Sweatpants","Pants","Unisex - Kinder","Jungen","Mädchen","305530031","Baumwolle","Baumwolle","70% Baumwolle, 30% Polyester","von links waschen, bis maximal 30°C"," ","Ohne Arm"," ","Hose","Hosen","Sporthose","Sporthosen","Freizeithose, Freizeithosen, Laufhose, Laufhosen"),
(0,"605","Frauen Kapuzenpullover mit V-Ausschnitt","Sweater","Damen","Mädchen","","78700031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","Lang - regulär","V-Ausschnitt","Sweatshirt","Sweatshirts","Hoodie","Hoodies","Sweater, Sweaters"),
(0,"610","Bandana","Accessory","Unisex - Erwachsene","Herren","Damen","78793031","Baumwolle","Baumwolle","80% Baumwolle, 20% Polyester",""," ","Ohne Arm"," ","Halstuch","Halstücher","","",""),
(0,"612","Frauen Trainingshose Hannah von IVEE","Pants","Damen","Mädchen","","305530031","Viskose","Viskose","65% Viskose aus Bambus, 28 % Baumwolle, 7% Elastan","von links waschen, bis maximal 30°C"," "," "," ","Hose","Hosen","Sporthose","Sporthosen","Freizeithose, Freizeithosen, Laufhose, Laufhosen"),
(0,"616","Männer Freizeitjacke mit Goldstreifen","Outerwear","Herren","Jungen","","78741031","Baumwolle","Baumwolle","80% Baumwolle, 20% Polyester","von links waschen, bis maximal 30°C"," ","Lang - regulär","Rundhals","Jacke","Jacken","Freizeitjacke","Sportjacke",""),
(0,"617","Frauen Freizeitjacke mit Goldstreifen","Outerwear","Damen","Mädchen","","78741031","Baumwolle","Baumwolle","80% Baumwolle, 20% Polyester","von links waschen, bis maximal 30°C"," ","Lang - regulär","Rundhals","Jacke","Jacken","Freizeitjacke","Sportjacke",""),
(0,"618","Bademantel","Swimwear","Unisex - Erwachsene","Herren","Damen","10739801","Baumwolle","Baumwolle","60% Baumwolle, 40% Polyester","von links waschen, bis maximal 30°C"," ","Lang - regulär","","Bademantel","Bademäntel","Morgenmantel","Morgenmäntel",""),
(0,"621","Männer Softshell Kapuzenjacke","Outerwear","Herren","Jungen","","78741031","Polyester","Polyester","94% Polyester, 6% Elastan","von links waschen, bis maximal 30°C"," ","Lang - regulär","Rundhals","Jacke","Jacken","Regenjacke","Regenjacken","Kapuzenjacke, Kapuzenjacken"),
(0,"622","Frauen Softshell Kapuzenjacke","Outerwear","Damen","Mädchen","","78741031","Polyester","Polyester","94% Polyester, 6% Elastan","von links waschen, bis maximal 30°C"," ","Lang - regulär","Rundhals","Jacke","Jacken","Regenjacke","Regenjacken","Kapuzenjacke, Kapuzenjacken"),
(0,"631","Frauen T-Shirt klassisch","Shirt","Damen","Mädchen","","305555031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"632","Männer Langarmshirt mit Kapuze","Shirt","Herren","Jungen","","305557031","Polyester","Polyester","50% Polyester, 37,5% Baumwolle, 12,5% Viskose","von links waschen, bis maximal 30°C"," ","Lang - regulär","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"633","Frauen Cardigan","Shirt","Damen","Mädchen","","78701031","Baumwolle","Baumwolle","50% Baumwolle, 50% Polyester","von links waschen, bis maximal 30°C"," ","Lang - regulär","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"635","Männer T-Shirt klimaneutral","Shirt","Herren","Jungen","","305555031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"639","Frauen Fitness Shorts","Shorts","Damen","Mädchen","","78723031","Baumwolle","Baumwolle","95% Baumwolle, 5% Spandex","von links waschen, bis maximal 30°C"," ","Ohne Arm"," ","Hose","Hosen","Höschen","Kurze Hose","Kurze Hosen"),
(0,"640","Männer Shorts","Shorts","Herren","Jungen","","78723031","Baumwolle","Baumwolle","93% Baumwolle, 7% Polyester","von links waschen, bis maximal 30°C"," ","Ohne Arm"," ","Hose","Hosen","Höschen","Kurze Hose","Kurze Hosen"),
(0,"641","Männer ärmelloser Kapuzenpullover","Sweater","Herren","Jungen","","78700031","Baumwolle","Baumwolle","93% Baumwolle, 7% Polyester","von links waschen, bis maximal 30°C"," ","Ohne Arm","Rundhals","Sweatshirt","Sweatshirts","Hoodie","Hoodies","Sweater, Sweaters"),
(0,"644","Männer Trainingsjacke","Outerwear","Herren","Jungen","","78741031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","Lang - regulär","Rundhals","Jacke","Jacken","Trainingsjacke","Trainingsjacken","Freizeitjacke, Freizeitjacken"),
(0,"645","Frauen Trainingsjacke","Outerwear","Damen","Mädchen","","78741031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","Lang - regulär","Rundhals","Jacke","Jacken","Trainingsjacke","Trainingsjacken","Freizeitjacke, Freizeitjacken"),
(0,"646","Männer Fußball Fanshirt","Shirt","Herren","Jungen","","305555031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"647","Männer Neon T-Shirt","Shirt","Herren","Jungen","","305555031","Polyester","Polyester","60% Polyester, 40% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"648","Frauen Neon T-Shirt","Shirt","Damen","Mädchen","","305555031","Polyester","Polyester","60% Polyester, 40% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"655","Frauen Kleid FREDERIKE von FRISURclothing","Dress","Damen","Mädchen","","78732031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","Ohne Arm","Rundhals","Kleid","Kleider","Kleidchen","Rock","Röcke"),
(0,"656","Frauen Kapuzenpullover MALIN von FRISURclothing","Sweater","Damen","Mädchen","","78700031","Baumwolle","Baumwolle","50% Baumwolle, 50% Polyacryl","von links waschen, bis maximal 30°C"," ","Lang - regulär","Rundhals","Sweatshirt","Sweatshirts","Hoodie","Hoodies","Sweater, Sweaters"),
(0,"657","Männer Kapuzenpullover MALTE von FRISURclothing","Sweater","Herren","Jungen","","78700031","Baumwolle","Baumwolle","50% Baumwolle, 50% Polyacryl","von links waschen, bis maximal 30°C"," ","Lang - regulär","Rundhals","Sweatshirt","Sweatshirts","Hoodie","Hoodies","Sweater, Sweaters"),
(0,"658","Männer Jersey-Sakko GEORG von von FRISURclothing","Suit","Herren","Jungen","","78738031","Baumwolle","Baumwolle","65% Baumwolle, 35% Polyester","von links waschen, bis maximal 30°C"," ","Lang - regulär","Rundhals","Sakko","Sakkos","Jackett","Jacketts","Sacco, Saccos"),
(0,"662","Frauen Übergrößenshirt","Shirt","Damen","Mädchen","","305555031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"663","Männer Übergrößenshirt","Shirt","Herren","Jungen","","305555031","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts"),
(0,"664","Baby T-Shirt","Shirt","Unisex - Baby","Baby - Jungen","Baby - Mädchen","364885011","Baumwolle","Baumwolle","100% Baumwolle","von links waschen, bis maximal 30°C"," ","1/2-Arm","Rundhals","T-Shirt","T-Shirts","Tshirt","Tshirts","Tee Shirt, Tee Shirts");
insert into amazon_color_mapping ( version, spreadshirt_color_id, spreadshirt_name,amazon_name) values 
(0,"1","white","Weiß"),
(0,"2","black","Schwarz"),
(0,"3","sky","Blau"),
(0,"4","navy","Blau"),
(0,"5","red","Rot"),
(0,"6","ash","Grau"),
(0,"7","yellow","Gelb"),
(0,"8","green","Grün"),
(0,"9","sand","Beige"),
(0,"10","white/white","Weiß"),
(0,"11","white/blue","Weiß"),
(0,"12","beige/black","Beige"),
(0,"13","blue/blue","Blau"),
(0,"14","black/black","Schwarz"),
(0,"15","lime","Gelb"),
(0,"16","khaki","Oliv"),
(0,"17","royal blue","Blau"),
(0,"18","light pink","Pink"),
(0,"19","olive/yellow","Oliv"),
(0,"20","powder blue","Blau"),
(0,"21","olive","Oliv"),
(0,"22","bordeaux","Rot"),
(0,"23","sand/charcoal","Beige"),
(0,"24","olive/black","Oliv"),
(0,"25","sky/navy","Blau"),
(0,"26","white/navy","Weiß"),
(0,"27","white/bordeaux","Weiß"),
(0,"28","pink","Pink"),
(0,"29","orange","Orange"),
(0,"30","neon green","Grün"),
(0,"31","dark green","Grün"),
(0,"32","beige","Beige"),
(0,"33","grey","Grau"),
(0,"34","yellow","Gelb"),
(0,"35","iris","Blau"),
(0,"36","olive","Oliv"),
(0,"37","silver","Silber"),
(0,"38","dark silver","Silber"),
(0,"39","sun yellow","Gelb"),
(0,"40","marine","Blau"),
(0,"41","blue/white","Blau"),
(0,"42","yellow/green","Gelb"),
(0,"43","white/germany","Weiß"),
(0,"44","white/austria","Weiß"),
(0,"45","yellow/black","Gelb"),
(0,"46","blue/black","Blau"),
(0,"47","red/black","Rot"),
(0,"48","red/white","Rot"),
(0,"49","sky/navy","Blau"),
(0,"50","wine/navy","Rot"),
(0,"51","beige/khaki","Beige"),
(0,"52","cream/safari","Elfenbein"),
(0,"53","white/rose","Weiß"),
(0,"54","black/white","Schwarz"),
(0,"55","dark red","Rot"),
(0,"56","sahara","Beige"),
(0,"57","safari","Grün"),
(0,"58","rose","Rot"),
(0,"59","cream","Beige"),
(0,"60","wine","Rot"),
(0,"61","camel","Beige"),
(0,"62","dark navy","Blau"),
(0,"63","sky blue","Blau"),
(0,"64","dark orange","Orange"),
(0,"65","midnight blue","Blau"),
(0,"66","bottlegreen","Grün"),
(0,"67","denim blue","Blau"),
(0,"68","granite","Grau"),
(0,"69","cappu","Braun"),
(0,"70","white/black","Weiß"),
(0,"71","white/red","Weiß"),
(0,"72","heather blue","Blau"),
(0,"73","heather green","Grün"),
(0,"74","heather red","Rot"),
(0,"75","heather brown","Braun"),
(0,"76","plum","Rot"),
(0,"77","nature","Beige"),
(0,"78","white/royal","Weiß"),
(0,"79","powderblue/charcoal","Blau"),
(0,"80","white/green","Weiß"),
(0,"81","black/yellow","Schwarz"),
(0,"82","mandarine/red","Orange"),
(0,"83","flamingo/red","Pink"),
(0,"84","lime/green","Grün"),
(0,"85","aqua","Blau"),
(0,"86","white/light blue","Weiß"),
(0,"87","orange/blue","Orange"),
(0,"88","grass green","Grün"),
(0,"89","deep olive/sun","Oliv"),
(0,"90","pink/white","Pink"),
(0,"91","orange/black","Orange"),
(0,"92","kelly green","Grün"),
(0,"93","azalea","Pink"),
(0,"94","chocolate","Braun"),
(0,"95","orange","Orange"),
(0,"96","kiwi","Grün"),
(0,"97","chocolate/sun","Braun"),
(0,"98","orange","Orange"),
(0,"99","pink","Pink"),
(0,"100","banana","Gelb"),
(0,"101","green/white","Grün"),
(0,"102","green/white","Grün"),
(0,"103","chocolate/tan","Braun"),
(0,"104","pumpkin/bark","Orange"),
(0,"105","charcoal/maroon","Grau"),
(0,"106","cocao/wine","Braun"),
(0,"107","mustard/navy","Gelb"),
(0,"108","pink/red","Pink"),
(0,"109","black/red","Schwarz"),
(0,"110","salmon","Braun"),
(0,"111","cigar","Braun"),
(0,"112","denim","Blau"),
(0,"113","heather grey/red","Grau"),
(0,"114","lemon","Gelb"),
(0,"115","brick red","Rot"),
(0,"116","apple/lemon","Grün"),
(0,"117","light grey/dark grey","Grau"),
(0,"118","pink/brown","Pink"),
(0,"119","seafoam/orange","Blau"),
(0,"120","brown","Braun"),
(0,"121","grey","Grau"),
(0,"122","army","Grün"),
(0,"123","gold/black","Gold"),
(0,"124","powder blue/red","Blau"),
(0,"125","navy/royal","Blau"),
(0,"126","navy","Blau"),
(0,"127","washed yellow","Gelb"),
(0,"128","white/brown","Weiß"),
(0,"129","asphalt","Grau"),
(0,"130","army","Grün"),
(0,"131","eggplant","Braun"),
(0,"132","white/france","Weiß"),
(0,"133","light navy","Blau"),
(0,"134","purple","Violett"),
(0,"135","gold ","Gold"),
(0,"136","charcoal","Grau"),
(0,"137","white/teal","Weiß"),
(0,"138","sherbert","Gelb"),
(0,"139","violet","Violett"),
(0,"140","creme","Elfenbein"),
(0,"141","lavender","Violett"),
(0,"142","fuchsia","Rot"),
(0,"143","raspberry","Rot"),
(0,"144","teal","Blau"),
(0,"145","baby blue","Blau"),
(0,"146","light blue","Blau"),
(0,"147","cranberry","Rot"),
(0,"148","sangria","Rot"),
(0,"149","coral","Orange"),
(0,"150","purple","Violett"),
(0,"151","sea foam","Blau"),
(0,"152","mint","Grün"),
(0,"153","forest","Grün"),
(0,"154","slate","Grau"),
(0,"155","pink/white","Pink"),
(0,"156","blue/white","Blau"),
(0,"157","Spring","Grün"),
(0,"158","Summer","Gelb"),
(0,"159","Autumn","braun"),
(0,"160","Winter","Weiß"),
(0,"161","Black","Schwarz"),
(0,"162","Camouflage","Oliv"),
(0,"163","loden","Oliv"),
(0,"164","deep heather","Grau"),
(0,"165","navy/white","Blau"),
(0,"166","white/lime","Weiß"),
(0,"167","white/fuchsia","Weiß"),
(0,"168","white/aquatic blue","Weiß"),
(0,"169","white/orange sherbert","Weiß"),
(0,"170","yellow/red","Gelb"),
(0,"171","green/black","Grün"),
(0,"172","light aqua","Blau"),
(0,"173","heron blue","Blau"),
(0,"174","dahlia","Violett"),
(0,"175","light grey","Grau"),
(0,"176","coal","Grau"),
(0,"177","ice blue","Blau"),
(0,"178","olive","Oliv"),
(0,"179","west sand","Beige"),
(0,"180","melange pink","Pink"),
(0,"181","melange purple","Violett"),
(0,"182","melange charcoal","Grau"),
(0,"183","melange sky blue","Blau"),
(0,"184","melange raspberry","Rot"),
(0,"185","melange chocolate","Braun"),
(0,"186","melange green","Grün"),
(0,"187","melange blue","Blau"),
(0,"188","brown/orange","Braun"),
(0,"189","pink/white","Pink"),
(0,"190","babyblue/white","Blau"),
(0,"191","mintgreen/white","Grün"),
(0,"192","white grid camouflage","Weiß"),
(0,"193","light pink","Pink"),
(0,"194","azalea","Pink"),
(0,"195","aqua","Blau"),
(0,"196","red","Rot"),
(0,"197","grey/white","Grau"),
(0,"198","brown/white","Braun"),
(0,"199","mint green","Grün"),
(0,"200","red/black","Rot"),
(0,"201","aqua/lime","Blau"),
(0,"202","lightpink/fuchsia","Pink"),
(0,"203","turquois","Blau"),
(0,"204","white/grey","Weiß"),
(0,"205","indigo blue","Blau"),
(0,"206","charcoal","Grau"),
(0,"207","forrest","Grün"),
(0,"208","blue/white","Blau"),
(0,"209","red/white","Rot"),
(0,"210","green/white ","Grün"),
(0,"211","bordeaux/white","Rot"),
(0,"212","royalblue/white","Blau"),
(0,"213","lavender","Violett"),
(0,"214","rose wine","Rot"),
(0,"215","washed cherry","Rot"),
(0,"216","washed black","Schwarz"),
(0,"217","washed pink","Pink"),
(0,"218","nude","Elfenbein"),
(0,"219","deep mint","Grün"),
(0,"220","petrol","Blau"),
(0,"221","heather grey stripe","Grau"),
(0,"222","ash white stripe","Grau"),
(0,"223","petal pink","Pink"),
(0,"224","Heather Oatmeal","Grau"),
(0,"225","Heather Red","Rot"),
(0,"226","Heather Green","Grün"),
(0,"227","Heather Chocolate","Braun"),
(0,"228","Heather Black","Schwarz"),
(0,"229","Heather Navy","Blau"),
(0,"230","leafgreen","Grün"),
(0,"231","heather grey","Grau"),
(0,"232","black/germany","Schwarz"),
(0,"233","black/austria","Schwarz"),
(0,"234","pastel green","Grün"),
(0,"235","dijon mustard","Gelb"),
(0,"236","pink","Pink"),
(0,"237","brown / sand","Braun"),
(0,"238","light blue / white","Blau"),
(0,"239","sky","Blau"),
(0,"240","king's blue","Blau"),
(0,"241","purple","Violett"),
(0,"242","galaxy","Blau"),
(0,"243","light scarlet","Rot"),
(0,"244","fairway green","Grün"),
(0,"245","light pink","Pink"),
(0,"246","dark red","Rot"),
(0,"247","grass green","Grün"),
(0,"248","khaki green","Grün"),
(0,"249","burgundy red","Rot"),
(0,"250","egg yellow","Gelb"),
(0,"251","heather grey","Grau"),
(0,"252","spider black","Schwarz"),
(0,"253","spider baby blue","Blau"),
(0,"254","spider red","Rot"),
(0,"255","spider navy","Blau"),
(0,"256","spider pink","Pink"),
(0,"257","light blue","Blau"),
(0,"258","royal blue","Blau"),
(0,"259","clover green","Grün"),
(0,"260","sage green","Grün"),
(0,"261","classic red","Rot"),
(0,"262","medium navy","Blau"),
(0,"263","cream","Elfenbein"),
(0,"264","bright navy","Blau"),
(0,"265","white/pink","Weiß"),
(0,"266","orange","Orange"),
(0,"267","black/blue","Schwarz"),
(0,"268","mallow ","Grau"),
(0,"269","dark blue","Blau"),
(0,"270","terracotta","Orange"),
(0,"271","natural brown","Braun"),
(0,"272","grey","Grau"),
(0,"273","washed navy","Blau"),
(0,"274","carbon black / striped asphalt","Schwarz"),
(0,"275","dark washed navy","Blau"),
(0,"276","ash-grey","Grau"),
(0,"277","purple","Violett"),
(0,"278","medium heather – black","Schwarz"),
(0,"279","slate – grizzly","Grau"),
(0,"280","ash-grey apricot","Grau"),
(0,"281","sunshine","Gelb"),
(0,"282","lapis blue","Blau"),
(0,"283","cyan","Blau"),
(0,"284","chocolate brown","Braun"),
(0,"285","pistachio","Grün"),
(0,"286","pomegranate","Rot"),
(0,"287","purple","Violett"),
(0,"288","cinder","Grau"),
(0,"289","light blue / white","Blau"),
(0,"290","pink/white","Pink"),
(0,"291","jeans blue","Blau"),
(0,"292","leaf green","Grün"),
(0,"293","peacock-blue","Blau"),
(0,"294","neon pink","Pink"),
(0,"295","dark red","Rot"),
(0,"296","light green","Grün"),
(0,"297","silver","Silber"),
(0,"298","crimson","Braun"),
(0,"299","emerald green","Grün"),
(0,"300","brown","Braun"),
(0,"301","lemon yellow","Gelb"),
(0,"302","light purple","Violett"),
(0,"303","chocolate brown","Braun"),
(0,"304","sea blue","Blau"),
(0,"305","light green","Grün"),
(0,"306","peacock-blue","Blau"),
(0,"307","graphite grey","Grau"),
(0,"308","grape juice/asphalt","Rot"),
(0,"309","black/asphalt","Schwarz"),
(0,"310","purple","Violett"),
(0,"311","aqua green","Grün"),
(0,"312","plum","Braun"),
(0,"313","sky blue","Blau"),
(0,"314","fuchsia red","Rot"),
(0,"315","peacock blue","Blau"),
(0,"316","gold","Gold"),
(0,"317","royal blue","Blau"),
(0,"318","jeans blue","Blau"),
(0,"319","army green","Grün"),
(0,"320","navy","Blau"),
(0,"321","ruby red","Rot"),
(0,"322","indigo","Blau"),
(0,"323","sand beige","Beige"),
(0,"324","moss green","Grün"),
(0,"325","leaf green","Grün"),
(0,"326","sea blue","Blau"),
(0,"327","red currant","Rot"),
(0,"328","steel blue","Blau"),
(0,"329","navy","Blau"),
(0,"330","dark navy","Blau"),
(0,"331","melange tan/brown","Elfenbein"),
(0,"332","melange blue/navy","Blau"),
(0,"333","natural white","Weiß"),
(0,"334","chintz rose","Rosa"),
(0,"335","dark navy","Blau"),
(0,"336","evergreen","Grün"),
(0,"337","sand beige","Beige"),
(0,"338","royal blue","Blau"),
(0,"339","asphalt","Grau"),
(0,"340","wine/navy","Rot"),
(0,"341","navy/heather grey","Blau"),
(0,"342","dijon mustard","Gelb"),
(0,"343","sand","Beige"),
(0,"344","navy","Blau"),
(0,"345","red","Rot"),
(0,"346","crystal pink","Pink"),
(0,"347","cyan","Blau"),
(0,"348","navy","Blau"),
(0,"349","pink","Pink"),
(0,"350","king's blue","Blau"),
(0,"351","light heather grey","Grau"),
(0,"352","light blue","Blau"),
(0,"353","mocha","Braun"),
(0,"354","light red","Rot"),
(0,"355","dark navy","Blau"),
(0,"356","brown","Braun"),
(0,"357","magenta","Violett"),
(0,"359","royal blue","Blau"),
(0,"360","evergreen","Grün"),
(0,"361","natural white","Weiß"),
(0,"362","dark pink","Pink"),
(0,"363","salt & pepper","Grau"),
(0,"364","red","Rot"),
(0,"365","navy","Blau"),
(0,"366","red","Rot"),
(0,"367","red","Rot"),
(0,"368","Camouflage","Oliv"),
(0,"369","neon pink","Pink"),
(0,"370","royal blue","Blau"),
(0,"371","red/asphalt","Rot"),
(0,"372","black/asphalt","Schwarz"),
(0,"373","white/grau","Weiß"),
(0,"374","umbra grey / wine red","Grau"),
(0,"375","umbra grey / clay brown","Grau"),
(0,"376","red","Rot"),
(0,"377","ash","Grau"),
(0,"378","red","Rot"),
(0,"379","cream white","Weiß"),
(0,"380","navy","Blau"),
(0,"381","birch","Grau"),
(0,"382","Spring/Summer","Grün"),
(0,"383","Birthday","Gelb"),
(0,"384","Valentine's Day","Violett"),
(0,"385","navy","Blau"),
(0,"386","pink","Pink"),
(0,"387","noble brown","Braun"),
(0,"388","diva blue","Blau"),
(0,"389","golden orange","Orange"),
(0,"390","mint green","Grün"),
(0,"391","pink lady","Pink"),
(0,"392","sky","Blau"),
(0,"393","purple","Violett"),
(0,"394","yellow","Gelb"),
(0,"395","leaf green","Grün"),
(0,"396","lilac","Violett"),
(0,"397","heather oatmeal","Grau"),
(0,"398","moss green","Grün"),
(0,"399","navy","Blau"),
(0,"400","black/ash","Schwarz"),
(0,"401","red/ash","Rot"),
(0,"402","petrol/ash","Grau"),
(0,"403","sage","Grün"),
(0,"404","natur","Elfenbein"),
(0,"405","blue/white","Blau"),
(0,"406","red/green","Rot"),
(0,"407","yellow/green","Gelb"),
(0,"408","orange/white","Orange"),
(0,"409","burgundy red/white","Rot"),
(0,"410","blue/white","Blau"),
(0,"411","washed burgundy","Rot"),
(0,"412","neon pink","Pink"),
(0,"413","neon yellow","Gelb"),
(0,"414","neon orange","Orange"),
(0,"415","pink/fuchsia","Rot"),
(0,"416","raspberry","Pink"),
(0,"417","brown","Braun"),
(0,"418","royal blue","Blau"),
(0,"419","light green","Grün"),
(0,"420","orange","Orange"),
(0,"421","red","Rot"),
(0,"422","silver/orange","Silber"),
(0,"423","royal blue/light turquoise","Blau"),
(0,"424","pink","Pink"),
(0,"425","baby blue","Blau"),
(0,"426","kelly green","Grün"),
(0,"427","grey/dark red","Grau"),
(0,"428","grey/pastell lila","Grau"),
(0,"429","blue/white","Blau"),
(0,"430","heather grey/blue","Grau"),
(0,"431","lapis blue","Blau"),
(0,"432","heather grey/yellow","Grau"),
(0,"433","dark red/white","Rot"),
(0,"434","heather grey/blue","Grau"),
(0,"435","green/white","Grün"),
(0,"436","rose shadow","Rosa"),
(0,"437","candy pink","Pink"),
(0,"438","forest green","Grün"),
(0,"439","kelly green","Grün"),
(0,"440","navy","Blau"),
(0,"441","mint green","Grün"),
(0,"442","crystal pink","Pink"),
(0,"443","powderblue","Blau"),
(0,"444","purple","Violett"),
(0,"445","light navy","Blau");

update amazon_product_type set size_chart = concat('/opt/j2ee/local/webapps-data/amazonas/sizecharts/',spreadshirt_product_type_id,'.png') where
spreadshirt_product_type_id in (101,108,114,123,141,144,146,148,15,160,172,174,175,20,202,207,209,216,23,25,266,267,281,288,3,300,302,342,357,36,361,362,368,369,372,375,376,377,379,381,428,430,444,445,457,461,463,464,48,483,487,492,493,494,495,5,51,526,530,538,539,54,543,549,553,555,560,561,562,565,567,57,570,571,574,575,580,584,593,6,601,602,604,605,610,612,616,618,621,622,631,632,633,635,639,64,640,641,644,645,646,647,648,655,656,657,658,662,663,664,69,70,84,93,95);