<?php

require_once 'RestRequest.php';

// class auto-generated by REST Compile
class ArticleCDO {

  // class variables
  private $requestUri = 'http://api.spreadshirt.net/api/v1/shops/264433/articles/7371156';

  private $articleID;
  private $price;
  private $productID;
  private $resourceLink;
  private $productLink;

  // constructor
  public function __construct($shopId, $articleId) {
        $rest = new RestRequest();

        $this->requestUri='http://api.spreadshirt.net/api/v1/shops/'.$shopId.'/articles/'.$articleId;
        $xml = simplexml_load_string( $rest->submit($this->requestUri) ); //->children('http://api.spreadshirt.net');

        $this->articleID = (String) $xml->attributes()->id;
        $this->price = (String) $xml->price->vatIncluded;
        $this->productLink = (String) $xml->product->attributes('http://www.w3.org/1999/xlink');
        $this->productID = (String) $xml->product['id'];
        $this->resourceLink = (String) $xml->resources->resource->attributes('http://www.w3.org/1999/xlink');
  }


  public function getPrice() {
    return $this->price;
  }

  public function getResourceLink() {
    return $this->resourceLink;
  }

  public function getProductLink() {
    return $this->productLink;
  }

  public function getProductID() {
    return $this->productID;
  }

  public function getArticleUrl() {
      return $this->requestUri;
  }

  public function getArticleID() {
      return $this->articleID;
  }

}

?>